import type { TokenBalanceRow } from "./types";

export const mockTokenBalanceData: TokenBalanceRow[] = [
  {
    id: "tb-001",
    tokenMasked: "sk_••••••••••••bal1",
    traderId: "trader-alpha",
    traderName: "Trader Alpha",
    amount: 5000,
    status: "active",
    usedAt: null,
    createdAt: "2025-03-01T09:00:00Z",
    createdBy: "admin@explat.com",
  },
  {
    id: "tb-002",
    tokenMasked: "sk_••••••••••••bal2",
    traderId: "trader-beta",
    traderName: "Trader Beta",
    amount: 10000,
    status: "used",
    usedAt: "2025-03-02T11:30:00Z",
    createdAt: "2025-02-28T14:00:00Z",
    createdBy: "admin@explat.com",
  },
  {
    id: "tb-003",
    tokenMasked: "sk_••••••••••••bal3",
    traderId: "trader-gamma",
    traderName: "Trader Gamma",
    amount: 2500,
    status: "active",
    usedAt: null,
    createdAt: "2025-03-02T08:15:00Z",
    createdBy: "support@explat.com",
  },
  {
    id: "tb-004",
    tokenMasked: "sk_••••••••••••bal4",
    traderId: "trader-delta",
    traderName: "Trader Delta",
    amount: 7500,
    status: "expired",
    usedAt: null,
    createdAt: "2025-02-20T10:00:00Z",
    createdBy: "admin@explat.com",
  },
  {
    id: "tb-005",
    tokenMasked: "sk_••••••••••••bal5",
    traderId: "trader-alpha",
    traderName: "Trader Alpha",
    amount: 3000,
    status: "used",
    usedAt: "2025-03-01T16:45:00Z",
    createdAt: "2025-02-25T12:00:00Z",
    createdBy: "admin@explat.com",
  },
];
