import type { TokenPayoutRow } from "./types";

export const mockTokenPayoutsData: TokenPayoutRow[] = [
  {
    id: "tp-001",
    tokenName: "Payout Token Alpha",
    traderId: "trader-alpha",
    traderName: "Trader Alpha",
    tokenMasked: "sk_••••••••••••xyz1",
    isActive: true,
    status: "active",
    createdAt: "2025-03-01T10:00:00Z",
    usedAt: null,
  },
  {
    id: "tp-002",
    tokenName: "Payout Token Beta",
    traderId: "trader-beta",
    traderName: "Trader Beta",
    tokenMasked: "sk_••••••••••••xyz2",
    isActive: false,
    status: "used",
    createdAt: "2025-02-28T14:30:00Z",
    usedAt: "2025-03-02T09:15:00Z",
  },
  {
    id: "tp-003",
    tokenName: "Payout Token Gamma",
    traderId: "trader-gamma",
    traderName: "Trader Gamma",
    tokenMasked: "sk_••••••••••••xyz3",
    isActive: true,
    status: "active",
    createdAt: "2025-03-02T08:00:00Z",
    usedAt: null,
  },
  {
    id: "tp-004",
    tokenName: "Payout Token Delta",
    traderId: "trader-delta",
    traderName: "Trader Delta",
    tokenMasked: "sk_••••••••••••xyz4",
    isActive: false,
    status: "expired",
    createdAt: "2025-02-20T12:00:00Z",
    usedAt: null,
  },
  {
    id: "tp-005",
    tokenName: "Payout Token Epsilon",
    traderId: "trader-alpha",
    traderName: "Trader Alpha",
    tokenMasked: "sk_••••••••••••xyz5",
    isActive: false,
    status: "used",
    createdAt: "2025-02-25T16:45:00Z",
    usedAt: "2025-03-01T11:20:00Z",
  },
];
