import type { DeviceRow } from "./types";

export const mockDevicesData: DeviceRow[] = [
  {
    id: "device-001",
    name: "Samsung A54 #1",
    requisiteId: "req-001",
    requisiteDisplay: "**** 4521",
    traderId: "trader-alpha",
    traderName: "Trader Alpha",
    battery: 87,
    operator: "МТС",
    isActive: true,
    healthcheck: "2025-03-02T10:15:00Z",
  },
  {
    id: "device-002",
    name: "iPhone 14 #2",
    requisiteId: "req-002",
    requisiteDisplay: "**** 8832",
    traderId: "trader-alpha",
    traderName: "Trader Alpha",
    battery: 42,
    operator: "Билайн",
    isActive: true,
    healthcheck: "2025-03-02T09:42:00Z",
  },
  {
    id: "device-003",
    name: "Xiaomi 13 #1",
    requisiteId: "req-003",
    requisiteDisplay: "**** 1209",
    traderId: "trader-beta",
    traderName: "Trader Beta",
    battery: 15,
    operator: "Мегафон",
    isActive: false,
    healthcheck: "2025-03-01T18:20:00Z",
  },
  {
    id: "device-004",
    name: "Samsung S24 #1",
    requisiteId: "req-004",
    requisiteDisplay: "**** 5566",
    traderId: "trader-delta",
    traderName: "Trader Delta",
    battery: 100,
    operator: "МТС",
    isActive: true,
    healthcheck: "2025-03-02T11:00:00Z",
  },
  {
    id: "device-005",
    name: "Pixel 8 #1",
    requisiteId: "req-005",
    requisiteDisplay: "**** 3344",
    traderId: "trader-epsilon",
    traderName: "Trader Epsilon",
    battery: 63,
    operator: "Теле2",
    isActive: true,
    healthcheck: "2025-03-02T08:33:00Z",
  },
];
