import type { TraderRow } from "./types";

export const mockTradersData: TraderRow[] = [
  {
    id: "trader-alpha",
    name: "Trader Alpha",
    balanceUsdt: 15200.5,
    balanceManat: 25840.85,
    method: "Card",
    priority: 85,
    conversionTransactions: 2.5,
    conversionPayouts: 1.2,
    requisitesCount: 4,
    activeOrdersCount: 12,
    isActive: true,
    trafficEnabled: true,
    payInEnabled: true,
    payOutEnabled: true,
    createdAt: "2025-01-10T09:00:00Z",
  },
  {
    id: "trader-beta",
    name: "Trader Beta",
    balanceUsdt: 8300.0,
    balanceManat: 14110.0,
    method: "Crypto",
    priority: 60,
    conversionTransactions: 1.8,
    conversionPayouts: 0.9,
    requisitesCount: 2,
    activeOrdersCount: 5,
    isActive: true,
    trafficEnabled: false,
    payInEnabled: true,
    payOutEnabled: false,
    createdAt: "2025-01-18T11:30:00Z",
  },
  {
    id: "trader-gamma",
    name: "Trader Gamma",
    balanceUsdt: 0,
    balanceManat: 0,
    method: "Card",
    priority: 40,
    conversionTransactions: 3.0,
    conversionPayouts: 0.0,
    requisitesCount: 1,
    activeOrdersCount: 0,
    isActive: false,
    trafficEnabled: false,
    payInEnabled: false,
    payOutEnabled: false,
    createdAt: "2025-02-05T14:00:00Z",
  },
  {
    id: "trader-delta",
    name: "Trader Delta",
    balanceUsdt: 25600.75,
    balanceManat: 43521.275,
    method: "Crypto",
    priority: 95,
    conversionTransactions: 2.0,
    conversionPayouts: 1.0,
    requisitesCount: 6,
    activeOrdersCount: 18,
    isActive: true,
    trafficEnabled: true,
    payInEnabled: true,
    payOutEnabled: true,
    createdAt: "2025-02-12T08:45:00Z",
  },
  {
    id: "trader-epsilon",
    name: "Trader Epsilon",
    balanceUsdt: 4200.0,
    balanceManat: 7140.0,
    method: "Card",
    priority: 70,
    conversionTransactions: 2.2,
    conversionPayouts: 1.1,
    requisitesCount: 3,
    activeOrdersCount: 7,
    isActive: true,
    trafficEnabled: true,
    payInEnabled: true,
    payOutEnabled: true,
    createdAt: "2025-02-20T16:20:00Z",
  },
];
