import type { AppealRow } from "./types";

export const mockAppealsData: AppealRow[] = [
  {
    id: "app-001",
    merchantId: "merchant-one",
    merchantName: "Merchant One",
    type: "pay-out",
    operationId: "pout-a1b2c3d4",
    traderId: "trader-alpha",
    traderName: "Trader Alpha",
    amount: 1500.5,
    status: "pending",
    timerSeconds: 1847,
    telegramSent: true,
    createdAt: "2025-03-02T10:30:00Z",
  },
  {
    id: "app-002",
    merchantId: "merchant-two",
    merchantName: "Merchant Two",
    type: "pay-out",
    operationId: "pout-e5f6g7h8",
    traderId: "trader-beta",
    traderName: "Trader Beta",
    amount: 2999.99,
    status: "resolved",
    timerSeconds: null,
    telegramSent: true,
    createdAt: "2025-03-01T14:20:00Z",
  },
  {
    id: "app-003",
    merchantId: "merchant-three",
    merchantName: "Merchant Three",
    type: "pay-in",
    operationId: "pout-i9j0k1l2",
    traderId: "trader-gamma",
    traderName: "Trader Gamma",
    amount: 750.0,
    status: "rejected",
    timerSeconds: null,
    telegramSent: false,
    createdAt: "2025-03-01T09:15:00Z",
  },
  {
    id: "app-004",
    merchantId: "merchant-one",
    merchantName: "Merchant One",
    type: "pay-in",
    operationId: "pout-q7r8s9t0",
    traderId: "trader-alpha",
    traderName: "Trader Alpha",
    amount: 890.25,
    status: "pending",
    timerSeconds: 332,
    telegramSent: true,
    createdAt: "2025-03-02T08:00:00Z",
  },
  {
    id: "app-005",
    merchantId: "merchant-four",
    merchantName: "Merchant Four",
    type: "pay-out",
    operationId: "pout-m3n4o5p6",
    traderId: "trader-delta",
    traderName: "Trader Delta",
    amount: 4200.0,
    status: "pending",
    timerSeconds: 125,
    telegramSent: false,
    createdAt: "2025-03-02T11:05:00Z",
  },
];
