import type { MerchantRow } from "./types";

export const mockMerchantsData: MerchantRow[] = [
  {
    id: "merchant-one",
    name: "Merchant One",
    login: "merchant_one@example.com",
    method: "Card",
    conversionTransactions: 2.5,
    conversionPayouts: 1.2,
    apiKeyMasked: "****4f2a",
    status: "active",
    createdAt: "2025-01-15T09:00:00Z",
  },
  {
    id: "merchant-two",
    name: "Merchant Two",
    login: "merchant_two@example.com",
    method: "Crypto",
    conversionTransactions: 1.8,
    conversionPayouts: 0.9,
    apiKeyMasked: "****b1c9",
    status: "active",
    createdAt: "2025-01-20T11:30:00Z",
  },
  {
    id: "merchant-three",
    name: "Merchant Three",
    login: "merchant_three@example.com",
    method: "Card",
    conversionTransactions: 3.0,
    conversionPayouts: 0.0,
    apiKeyMasked: "****7e3d",
    status: "inactive",
    createdAt: "2025-02-01T14:00:00Z",
  },
  {
    id: "merchant-four",
    name: "Merchant Four",
    login: "merchant_four@example.com",
    method: "Crypto",
    conversionTransactions: 2.0,
    conversionPayouts: 1.0,
    apiKeyMasked: "****9a2f",
    status: "active",
    createdAt: "2025-02-10T08:45:00Z",
  },
  {
    id: "merchant-five",
    name: "Merchant Five",
    login: "merchant_five@example.com",
    method: "Card",
    conversionTransactions: 2.2,
    conversionPayouts: 1.1,
    apiKeyMasked: "****c4e8",
    status: "active",
    createdAt: "2025-02-18T16:20:00Z",
  },
  {
    id: "merchant-six",
    name: "Merchant Six",
    login: "merchant_six@example.com",
    method: "Crypto",
    conversionTransactions: 1.5,
    conversionPayouts: 0.0,
    apiKeyMasked: "****1d6b",
    status: "inactive",
    createdAt: "2025-02-25T10:00:00Z",
  },
];
